import { FaReact, FaNodeJs, FaPython, FaJava, FaDatabase } from "react-icons/fa";
import {
	SiExpress,
	SiMongodb,
	SiTypescript,
	SiJavascript,
	SiHtml5,
	SiCss3,
	SiSpring,
	SiMicrosoftsqlserver,
	SiPostgresql,
	SiHibernate,
	SiBootstrap,
	SiVaadin,
	SiJira,
	SiJenkins,
	SiGit,
	SiApachemaven,
	SiGradle,
	SiGithubactions,
	SiGithub,
	SiBitbucket,
} from "react-icons/si";
import { AiOutlineApi } from "react-icons/ai";

export const projects = [
	{
		name: "OCP",
		image: "projects/OCP.png",
		details: "Web platform for hosting career pages and job listings.",
		stack: ["React 18", "Node.js", "Express", "MongoDB (Local, Atlas)"],
		demoLink: "#",
		repoLink: "https://github.com/IvanoskiHarmonia/open-career-portal",
	},
	{
		name: "StudySprint",
		image: "projects/StudySprint.png",
		details: "Dynamic quizzes tailored to your knowledge and preferences.",
		stack: ["React 18", "Spring Boot", "axios", "H2"],
		demoLink: "#",
		repoLink: "https://github.com/IvanoskiHarmonia/quiz-service",
	},
	{
		name: "3os",
		image: "projects/3os.png",
		details: "Digital evolution for enhanced academic growth.",
		stack: ["Web Flow", "Component-based", "UI/UX", "Salesforce"],
		demoLink: "https://www.3os.com/",
		repoLink: "https://github.com/Software-Engineering-1-Group-13/Bookstore-API",
	},
	{
		name: "Adorned",
		image: "projects/NoImage.jpg",
		details: "App to organize and match your wardrobe easily.",
		stack: ["Node.js", "Express", "PostgreSQL", "Bcrypt"],
		demoLink: "#",
		repoLink: "https://github.com/IvanoskiHarmonia/adorned",
	},
];

export const techStack = [
	{ name: "Java", icon: FaJava },
	{ name: "Spring", icon: SiSpring },
	{ name: "Python", icon: FaPython },
	{ name: "React", icon: FaReact },
	{ name: "Node.js", icon: FaNodeJs },
	{ name: "Express", icon: SiExpress },
	{ name: "TypeScript", icon: SiTypescript },
	{ name: "JavaScript", icon: SiJavascript },
	{ name: "SQL", icon: SiMicrosoftsqlserver },
	{ name: "PostgreSQL", icon: SiPostgresql },
	{ name: "MongoDB", icon: SiMongodb },
	{ name: "Hibernate", icon: SiHibernate },
	{ name: "H2", icon: FaDatabase },
	{ name: "RESTful APIs", icon: AiOutlineApi },
	{ name: "HTML", icon: SiHtml5 },
	{ name: "CSS", icon: SiCss3 },
	{ name: "Bootstrap", icon: SiBootstrap },
	{ name: "Vaadin", icon: SiVaadin },
	{ name: "Jenkins", icon: SiJenkins },
	{ name: "GitHub Actions", icon: SiGithubactions },
	{ name: "Git", icon: SiGit },
	{ name: "GitHub", icon: SiGithub },
	{ name: "BitBucket", icon: SiBitbucket },
	{ name: "Jira", icon: SiJira },
	{ name: "Maven", icon: SiApachemaven },
	{ name: "Gradle", icon: SiGradle },
];
